const demoAcc = {
  schedule: [
    {
      building: "School A",
      courseCode: "MTHXXXXA - 1",
      courseName: "Advanced Statistics S1",
      days: "A",
      markingPeriods: "Q1, Q2",
      periods: "1",
      room: "Room 1",
      status: "Active",
      teacher: "Teacher A",
    },
    {
      building: "School A",
      courseCode: "SCIXXXXA - 1",
      courseName: "Advanced Physics S1",
      days: "B",
      markingPeriods: "Q1, Q2",
      periods: "1",
      room: "Room 2",
      status: "Active",
      teacher: "Teacher B",
    },
    {
      building: "School A",
      courseCode: "MTHXXXXB - 1",
      courseName: "Advanced Statistics S2",
      days: "A",
      markingPeriods: "Q3, Q4",
      periods: "1",
      room: "Room 1",
      status: "Active",
      teacher: "Teacher A",
    },
    {
      building: "School A",
      courseCode: "SCIXXXXB - 1",
      courseName: "Advanced Physics S2",
      days: "B",
      markingPeriods: "Q3, Q4",
      periods: "1",
      room: "Room 2",
      status: "Active",
      teacher: "Teacher B",
    },
    {
      building: "School A",
      courseCode: "TECXXXXA - 1",
      courseName: "Computer Science Advanced S1",
      days: "A",
      markingPeriods: "Q1, Q2",
      periods: "2",
      room: "Room 3",
      status: "Active",
      teacher: "Teacher C",
    },
    {
      building: "School A",
      courseCode: "ELAXXXXA - 3",
      courseName: "Advanced English Literature S1",
      days: "B",
      markingPeriods: "Q1, Q2",
      periods: "2",
      room: "Room 4",
      status: "Active",
      teacher: "Teacher D",
    },
    {
      building: "School A",
      courseCode: "TECXXXXB - 1",
      courseName: "Computer Science Advanced S2",
      days: "A",
      markingPeriods: "Q3, Q4",
      periods: "2",
      room: "Room 3",
      status: "Active",
      teacher: "Teacher C",
    },
    {
      building: "School A",
      courseCode: "ELAXXXXB - 3",
      courseName: "Advanced English Literature S2",
      days: "B",
      markingPeriods: "Q3, Q4",
      periods: "2",
      room: "Room 4",
      status: "Active",
      teacher: "Teacher D",
    },
    {
      building: "School A",
      courseCode: "SSTXXXX - 1",
      courseName: "Advanced Government",
      days: "A",
      markingPeriods: "Q1, Q2",
      periods: "3",
      room: "Room 5",
      status: "Active",
      teacher: "Teacher E",
    },
    {
      building: "School A",
      courseCode: "ELCXXXXA - 2",
      courseName: "Course S1",
      days: "B",
      markingPeriods: "Q1, Q2",
      periods: "3",
      room: "Room 6",
      status: "Active",
      teacher: "Teacher F",
    },
    {
      building: "School A",
      courseCode: "SSTXXXX10 - 6",
      courseName: "Advanced Economics",
      days: "A",
      markingPeriods: "Q3, Q4",
      periods: "3",
      room: "Room 5",
      status: "Active",
      teacher: "Teacher G",
    },
    {
      building: "School A",
      courseCode: "ELCXXXXB - 2",
      courseName: "Course S2",
      days: "B",
      markingPeriods: "Q3, Q4",
      periods: "3",
      room: "Room 6",
      status: "Active",
      teacher: "Teacher F",
    },
    {
      building: "School A",
      courseCode: "GENXXXXA - 1",
      courseName: "General Studies S1",
      days: "A",
      markingPeriods: "Q1, Q2",
      periods: "4",
      room: "N/A",
      status: "Active",
      teacher: "Staff",
    },
    {
      building: "School A",
      courseCode: "GENXXXXA - 2",
      courseName: "General Studies S1",
      days: "B",
      markingPeriods: "Q1, Q2",
      periods: "4",
      room: "N/A",
      status: "Active",
      teacher: "Staff",
    },
    {
      building: "School A",
      courseCode: "GENXXXXB - 1",
      courseName: "General Studies S2",
      days: "A",
      markingPeriods: "Q3, Q4",
      periods: "4",
      room: "N/A",
      status: "Active",
      teacher: "Staff",
    },
    {
      building: "School A",
      courseCode: "GENXXXXB - 2",
      courseName: "General Studies S2",
      days: "B",
      markingPeriods: "Q3, Q4",
      periods: "4",
      room: "N/A",
      status: "Active",
      teacher: "Staff",
    },
    {
      building: "School A",
      courseCode: "COLXXXXA - 3",
      courseName: "Calculus Online S1",
      days: "A",
      markingPeriods: "Q1, Q2",
      periods: "AFT",
      room: "N/A",
      status: "Active",
      teacher: "Staff",
    },
    {
      building: "School A",
      courseCode: "COLXXXXB - 3",
      courseName: "Differential Equations Online S2",
      days: "A",
      markingPeriods: "Q3, Q4",
      periods: "AFT",
      room: "N/A",
      status: "Active",
      teacher: "Staff",
    },
    {
      building: "School A",
      courseCode: "MSCXXXXM - 18",
      courseName: "Senior Advisory",
      days: "A, B",
      markingPeriods: "Q1, Q2, Q3, Q4",
      periods: "ADV",
      room: "Room 7",
      status: "Active",
      teacher: "Teacher H",
    },
  ],
};

export default demoAcc;
