const demoData = {
  otherClasses: [
    {
      name: "Col Calc 3 Math 2415 ONLINE S1",
      grade: 0,
      lastUpdated: "",
      assignments: [],
      code: "COL45510",
      weights: {
        weight: 0,
      },
    },
    {
      name: "AP English Literature S1",
      grade: 95.42,
      lastUpdated: "9/13/2024",
      assignments: [
        {
          name: "2 Socratic Seminar",
          category: "Assessment of Learning",
          dateAssigned: "",
          dateDue: "09/19/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "1 Socratic Seminar",
          category: "Assessment of Learning",
          dateAssigned: "",
          dateDue: "09/19/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "2 Socratic Prep Ch. 2",
          category: "Progress Check for Learning",
          dateAssigned: "",
          dateDue: "09/17/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "1 Socratic Prep Ch. 1",
          category: "Progress Check for Learning",
          dateAssigned: "",
          dateDue: "09/13/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "5C HTRL Response",
          category: "Progress Check for Learning",
          dateAssigned: "",
          dateDue: "09/11/2024",
          score: "0",
          totalPoints: "100",
        },
        {
          name: "1-5 Elements of Lit Project",
          category: "Assessment of Learning",
          dateAssigned: "",
          dateDue: "09/09/2024",
          score: "100",
          totalPoints: "100",
        },
        {
          name: "1-5 Elements of Lit Chart",
          category: "Progress Check for Learning",
          dateAssigned: "",
          dateDue: "08/30/2024",
          score: "100",
          totalPoints: "100",
        },
        {
          name: "5A Literary Terms Quiz",
          category: "Assessment of Learning",
          dateAssigned: "",
          dateDue: "08/29/2024",
          score: "90.83",
          totalPoints: "100",
        },
        {
          name: "1-5 Lit Elements Packet",
          category: "Progress Check for Learning",
          dateAssigned: "",
          dateDue: "08/22/2024",
          score: "100",
          totalPoints: "100",
        },
        {
          name: "5A Lit Terms Chart",
          category: "Progress Check for Learning",
          dateAssigned: "",
          dateDue: "08/20/2024",
          score: "100",
          totalPoints: "100",
        },
      ],
      code: "ELA14300",
      weights: {
        name: "AP English Literature & Composition",
        weight: 6,
        multiplier: 1,
      },
    },
    {
      name: "ISM 1 S1",
      grade: 0,
      lastUpdated: "",
      assignments: [],
      code: "ELC14115",
      weights: {
        weight: 0,
      },
    },
    {
      name: "AP Statistics S1",
      grade: 94.33,
      lastUpdated: "9/10/2024",
      assignments: [
        {
          name: "PC 9/12-13",
          category: "Progress Check for Learning",
          dateAssigned: "09/12/2024",
          dateDue: "09/13/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "PC 9/6-9",
          category: "Progress Check for Learning",
          dateAssigned: "09/06/2024",
          dateDue: "09/09/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "Normal Distribution",
          category: "Assessment of Learning",
          dateAssigned: "09/04/2024",
          dateDue: "09/05/2024",
          score: "100",
          totalPoints: "100",
        },
        {
          name: "PC 8/29-30",
          category: "Progress Check for Learning",
          dateAssigned: "08/29/2024",
          dateDue: "08/30/2024",
          score: "L     - Late Work",
          totalPoints: "100",
        },
        {
          name: "PC 8/27-28",
          category: "Progress Check for Learning",
          dateAssigned: "08/27/2024",
          dateDue: "08/28/2024",
          score: "L     - Late Work",
          totalPoints: "100",
        },
        {
          name: "AoL 1-Variable Data",
          category: "Assessment of Learning",
          dateAssigned: "08/23/2024",
          dateDue: "08/26/2024",
          score: "83",
          totalPoints: "100",
        },
        {
          name: "Describing Distributions",
          category: "Assessment of Learning",
          dateAssigned: "08/21/2024",
          dateDue: "08/22/2024",
          score: "100",
          totalPoints: "100",
        },
        {
          name: "PC 8/21-22",
          category: "Progress Check for Learning",
          dateAssigned: "08/21/2024",
          dateDue: "08/22/2024",
          score: "L     - Late Work",
          totalPoints: "100",
        },
        {
          name: "PC 8/19-20",
          category: "Progress Check for Learning",
          dateAssigned: "08/19/2024",
          dateDue: "08/20/2024",
          score: "L     - Late Work",
          totalPoints: "100",
        },
        {
          name: "PC 8/15-16",
          category: "Progress Check for Learning",
          dateAssigned: "08/15/2024",
          dateDue: "08/16/2024",
          score: "L     - Late Work",
          totalPoints: "100",
        },
      ],
      code: "MTH45310",
      weights: {
        name: "AP Statistics",
        weight: 6,
        multiplier: 1,
      },
    },
    {
      name: "AP Physics C S1",
      grade: 94.5,
      lastUpdated: "9/7/2024",
      assignments: [
        {
          name: "Work, Energy and Power",
          category: "Assessment of Learning",
          dateAssigned: "",
          dateDue: "10/09/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "Unit 3 Progress Check MCQ AP Classroom",
          category: "Progress Check for Learning",
          dateAssigned: "",
          dateDue: "10/08/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "FRQ Block on a Ramp with Spring",
          category: "Progress Check for Learning",
          dateAssigned: "",
          dateDue: "10/04/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "Resistive Forces and Circular Motion",
          category: "Assessment of Learning",
          dateAssigned: "",
          dateDue: "09/27/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "Unit 2 Progress Check MCQ AP Classroom",
          category: "Progress Check for Learning",
          dateAssigned: "",
          dateDue: "09/25/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "Coffee Filter Lab",
          category: "Progress Check for Learning",
          dateAssigned: "",
          dateDue: "09/24/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "Newton's Laws and Center of Mass",
          category: "Assessment of Learning",
          dateAssigned: "",
          dateDue: "09/18/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "Modified Atwood's Lab",
          category: "Progress Check for Learning",
          dateAssigned: "",
          dateDue: "09/10/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "2D Kinematics",
          category: "Assessment of Learning",
          dateAssigned: "",
          dateDue: "09/04/2024",
          score: "93",
          totalPoints: "100",
        },
        {
          name: "Unit 1 Progress Check MCQ AP Classroom",
          category: "Progress Check for Learning",
          dateAssigned: "",
          dateDue: "08/30/2024",
          score: "0",
          totalPoints: "100",
        },
        {
          name: "Marble Launcher Lab",
          category: "Progress Check for Learning",
          dateAssigned: "",
          dateDue: "08/27/2024",
          score: "84",
          totalPoints: "100",
        },
        {
          name: "1D Kinematics",
          category: "Assessment of Learning",
          dateAssigned: "",
          dateDue: "08/23/2024",
          score: "96",
          totalPoints: "100",
        },
        {
          name: "Lab - Car Crash!",
          category: "Progress Check for Learning",
          dateAssigned: "",
          dateDue: "08/19/2024",
          score: "57",
          totalPoints: "100",
        },
      ],
      code: "SCI35500",
      weights: {
        name: "AP Physics C",
        weight: 6,
        multiplier: 2,
      },
    },
    {
      name: "AP Government",
      grade: 88.33,
      lastUpdated: "9/11/2024",
      assignments: [
        {
          name: "1A and 1B FRQ",
          category: "Assessment of Learning",
          dateAssigned: "10/04/2024",
          dateDue: "10/04/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "Socialization and Linkage Institutions MCQ Exam",
          category: "Assessment of Learning",
          dateAssigned: "10/03/2024",
          dateDue: "10/03/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "Voting and Linkage Institutions Vocab Quiz",
          category: "Progress Check for Learning",
          dateAssigned: "09/26/2024",
          dateDue: "09/26/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "Socialization Essay",
          category: "Assessment of Learning",
          dateAssigned: "09/16/2024",
          dateDue: "09/16/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "Socialization Essay Progress Check",
          category: "Progress Check for Learning",
          dateAssigned: "09/11/2024",
          dateDue: "09/11/2024",
          score: "CNS   - Completion No Score",
          totalPoints: "100",
        },
        {
          name: "FRQ Exam 1A",
          category: "Assessment of Learning",
          dateAssigned: "09/05/2024",
          dateDue: "09/05/2024",
          score: "100",
          totalPoints: "100",
        },
        {
          name: "Foundations of American Democracy MCQ Exam",
          category: "Assessment of Learning",
          dateAssigned: "09/05/2024",
          dateDue: "09/05/2024",
          score: "65",
          totalPoints: "100",
        },
        {
          name: "Foundations of American Democracy Vocabulary Quiz",
          category: "Progress Check for Learning",
          dateAssigned: "08/26/2024",
          dateDue: "08/26/2024",
          score: "80",
          totalPoints: "100",
        },
        {
          name: "Intro to American Gov Infographic Project",
          category: "Assessment of Learning",
          dateAssigned: "08/26/2024",
          dateDue: "08/26/2024",
          score: "100",
          totalPoints: "100",
        },
        {
          name: "Infographic Progress Check",
          category: "Progress Check for Learning",
          dateAssigned: "08/23/2024",
          dateDue: "08/23/2024",
          score: "0",
          totalPoints: "100",
        },
      ],
      code: "SST34300",
      weights: {
        name: "AP Government",
        weight: 6,
        multiplier: 1,
      },
    },
    {
      name: "Computer Sci 3 Adv S1",
      grade: 100,
      lastUpdated: "8/30/2024",
      assignments: [
        {
          name: "Unit01 Stacks (API)",
          category: "Assessment of Learning",
          dateAssigned: "",
          dateDue: "09/19/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "Unit01 Stacks  (array backed)",
          category: "Assessment of Learning",
          dateAssigned: "",
          dateDue: "09/19/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "Unit01 Stacks (MCQ)",
          category: "Progress Check for Learning",
          dateAssigned: "",
          dateDue: "09/17/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "Lab03 - Maze Solver (API)",
          category: "Progress Check for Learning",
          dateAssigned: "",
          dateDue: "09/17/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "Lab02 - My Stack (array backed)",
          category: "Progress Check for Learning",
          dateAssigned: "",
          dateDue: "09/09/2024",
          score: "",
          totalPoints: "100",
        },
        {
          name: "Unit 0 Review [AOL]",
          category: "Assessment of Learning",
          dateAssigned: "08/30/2024",
          dateDue: "08/30/2024",
          score: "100",
          totalPoints: "100",
        },
        {
          name: "Unit 0 Review [PC]",
          category: "Progress Check for Learning",
          dateAssigned: "08/26/2024",
          dateDue: "08/26/2024",
          score: "93.33",
          totalPoints: "100",
        },
        {
          name: "Game of Life Lab [PC]",
          category: "Progress Check for Learning",
          dateAssigned: "08/16/2024",
          dateDue: "08/20/2024",
          score: "100",
          totalPoints: "100",
        },
      ],
      code: "TEC22200",
      weights: {
        name: "Computer Science 3 Adv",
        weight: 6,
        multiplier: 1,
      },
    },
  ],
  periodNumber: 1,
};

export default demoData;
