const demoAcc = {
  transcript: [
    {
      yearsAttended: "Year1-Year2",
      gradeLevel: "09",
      building: "School A",
      totalCredits: "8.5000",
      courses: [
        {
          courseCode: "C001",
          courseName: "Course A",
          sem1Grade: "P",
          sem2Grade: "P",
          finalGrade: "",
          courseCredits: "1.0000",
          shouldAdd: false,
        },
        {
          courseCode: "C002",
          courseName: "Course B",
          sem1Grade: "P",
          sem2Grade: "P",
          finalGrade: "",
          courseCredits: "1.0000",
          shouldAdd: false,
        },
        {
          courseCode: "C003",
          courseName: "Course C",
          sem1Grade: "P",
          sem2Grade: "P",
          finalGrade: "",
          courseCredits: "1.0000",
          shouldAdd: false,
        },
        {
          courseCode: "C004",
          courseName: "Course D",
          sem1Grade: "P",
          sem2Grade: "P",
          finalGrade: "",
          courseCredits: "1.0000",
          shouldAdd: false,
        },
        {
          courseCode: "C005",
          courseName: "Course E",
          sem1Grade: "P",
          sem2Grade: "P",
          finalGrade: "",
          courseCredits: "1.0000",
          shouldAdd: false,
        },
        {
          courseCode: "C006",
          courseName: "Course F",
          sem1Grade: "P",
          sem2Grade: "P",
          finalGrade: "",
          courseCredits: "1.0000",
          shouldAdd: false,
        },
        {
          courseCode: "C007",
          courseName: "Course G",
          sem1Grade: "P",
          sem2Grade: "P",
          finalGrade: "",
          courseCredits: "1.0000",
          shouldAdd: false,
        },
        {
          courseCode: "C008",
          courseName: "Course H",
          sem1Grade: "P",
          sem2Grade: "",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: false,
        },
        {
          courseCode: "C009",
          courseName: "Course I",
          sem1Grade: "P",
          sem2Grade: "P",
          finalGrade: "",
          courseCredits: "1.0000",
          shouldAdd: false,
        },
      ],
    },
    {
      yearsAttended: "Year2-Year3",
      gradeLevel: "10",
      building: "School B",
      totalCredits: "8.5000",
      courses: [
        {
          courseCode: "C010",
          courseName: "Course J",
          sem1Grade: "95",
          sem2Grade: "",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: false,
        },
        {
          courseCode: "C011",
          courseName: "Course K",
          sem1Grade: "",
          sem2Grade: "92",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: false,
        },
        {
          courseCode: "C012",
          courseName: "Course L",
          sem1Grade: "96",
          sem2Grade: "",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: true,
        },
        {
          courseCode: "C013",
          courseName: "Course M",
          sem1Grade: "100",
          sem2Grade: "",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: true,
        },
        {
          courseCode: "C014",
          courseName: "Course N",
          sem1Grade: "98",
          sem2Grade: "",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: true,
        },
        {
          courseCode: "C015",
          courseName: "Course O",
          sem1Grade: "98",
          sem2Grade: "",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: true,
        },
        {
          courseCode: "C016",
          courseName: "Course P",
          sem1Grade: "99",
          sem2Grade: "",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: true,
        },
        {
          courseCode: "C017",
          courseName: "Course Q",
          sem1Grade: "",
          sem2Grade: "100",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: true,
        },
        {
          courseCode: "C018",
          courseName: "Course R",
          sem1Grade: "",
          sem2Grade: "100",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: true,
        },
        {
          courseCode: "C019",
          courseName: "Course S",
          sem1Grade: "",
          sem2Grade: "100",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: true,
        },
        {
          courseCode: "C020",
          courseName: "Course T",
          sem1Grade: "",
          sem2Grade: "96",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: true,
        },
        {
          courseCode: "C021",
          courseName: "Course U",
          sem1Grade: "",
          sem2Grade: "99",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: true,
        },
        {
          courseCode: "C022",
          courseName: "Course V",
          sem1Grade: "",
          sem2Grade: "100",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: true,
        },
        {
          courseCode: "C023",
          courseName: "Course W",
          sem1Grade: "",
          sem2Grade: "100",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: true,
        },
        {
          courseCode: "C024",
          courseName: "Course X",
          sem1Grade: "",
          sem2Grade: "96",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: true,
        },
        {
          courseCode: "C025",
          courseName: "Course Y",
          sem1Grade: "",
          sem2Grade: "99",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: true,
        },
        {
          courseCode: "C026",
          courseName: "Course Z",
          sem1Grade: "",
          sem2Grade: "100",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: true,
        },
        {
          courseCode: "C027",
          courseName: "Course AA",
          sem1Grade: "",
          sem2Grade: "100",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: true,
        },
        {
          courseCode: "C028",
          courseName: "Course AB",
          sem1Grade: "96",
          sem2Grade: "94",
          finalGrade: "",
          courseCredits: "1.0000",
          shouldAdd: true,
        },
      ],
    },
    {
      yearsAttended: "Year3-Year4",
      gradeLevel: "11",
      building: "School B",
      totalCredits: "8.5000",
      courses: [
        {
          courseCode: "C029",
          courseName: "Course AC",
          sem1Grade: "99",
          sem2Grade: "99",
          finalGrade: "",
          courseCredits: "1.0000",
          shouldAdd: true,
        },
        {
          courseCode: "C030",
          courseName: "Course AD",
          sem1Grade: "93",
          sem2Grade: "86",
          finalGrade: "",
          courseCredits: "1.0000",
          shouldAdd: true,
        },
        {
          courseCode: "C031",
          courseName: "Course AE",
          sem1Grade: "93",
          sem2Grade: "95",
          finalGrade: "",
          courseCredits: "1.0000",
          shouldAdd: true,
        },
        {
          courseCode: "C032",
          courseName: "Course AF",
          sem1Grade: "91",
          sem2Grade: "89",
          finalGrade: "",
          courseCredits: "1.0000",
          shouldAdd: true,
        },
        {
          courseCode: "C033",
          courseName: "Course AG",
          sem1Grade: "98",
          sem2Grade: "99",
          finalGrade: "",
          courseCredits: "1.0000",
          shouldAdd: true,
        },
        {
          courseCode: "C034",
          courseName: "Course AH",
          sem1Grade: "99",
          sem2Grade: "99",
          finalGrade: "",
          courseCredits: "1.0000",
          shouldAdd: true,
        },
        {
          courseCode: "C035",
          courseName: "Course AI",
          sem1Grade: "99",
          sem2Grade: "100",
          finalGrade: "",
          courseCredits: "1.0000",
          shouldAdd: true,
        },
        {
          courseCode: "C036",
          courseName: "Course AJ",
          sem1Grade: "94",
          sem2Grade: "94",
          finalGrade: "",
          courseCredits: "1.0000",
          shouldAdd: true,
        },
        {
          courseCode: "C037",
          courseName: "Course AK",
          sem1Grade: "96",
          sem2Grade: "",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: true,
        },
      ],
    },
    {
      yearsAttended: "Year4-Year5",
      gradeLevel: "12",
      building: "School B",
      totalCredits: "1.5000",
      courses: [
        {
          courseCode: "C038",
          courseName: "Course AL",
          sem1Grade: "",
          sem2Grade: "96",
          finalGrade: "",
          courseCredits: "0.5000",
          shouldAdd: true,
        },
        {
          courseCode: "C039",
          courseName: "Course AM",
          sem1Grade: "97",
          sem2Grade: "99",
          finalGrade: "",
          courseCredits: "1.0000",
          shouldAdd: true,
        },
        {
          courseCode: "C040",
          courseName: "Course AN",
          sem1Grade: "",
          sem2Grade: "",
          finalGrade: "",
          courseCredits: "0.0000",
          shouldAdd: false,
        },
        {
          courseCode: "C041",
          courseName: "Course AO",
          sem1Grade: "",
          sem2Grade: "",
          finalGrade: "",
          courseCredits: "0.0000",
          shouldAdd: false,
        },
        {
          courseCode: "C042",
          courseName: "Course AP",
          sem1Grade: "",
          sem2Grade: "",
          finalGrade: "",
          courseCredits: "0.0000",
          shouldAdd: false,
        },
        {
          courseCode: "C043",
          courseName: "Course AQ",
          sem1Grade: "",
          sem2Grade: "",
          finalGrade: "",
          courseCredits: "0.0000",
          shouldAdd: false,
        },
        {
          courseCode: "C044",
          courseName: "Course AR",
          sem1Grade: "",
          sem2Grade: "",
          finalGrade: "",
          courseCredits: "0.0000",
          shouldAdd: false,
        },
        {
          courseCode: "C045",
          courseName: "Course AS",
          sem1Grade: "",
          sem2Grade: "",
          finalGrade: "",
          courseCredits: "0.0000",
          shouldAdd: false,
        },
        {
          courseCode: "C046",
          courseName: "Course AT",
          sem1Grade: "",
          sem2Grade: "",
          finalGrade: "",
          courseCredits: "0.0000",
          shouldAdd: false,
        },
      ],
    },
  ],
};

export default demoAcc;
