export const demoData = {
  1: {
    data: [
      {
        courseCode: "ELA13300",
        courseName: "AP English Language",
        studentGrade: 95,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/05/2023",
            "10/03/2023",
            "1B - Timed Precis",
            "Assessment of Learning",
            "95.00",
            "100.00",
            "1.00",
            "95.00",
            "100.00",
            "95.000%",
          ],
          [
            "10/05/2023",
            "10/03/2023",
            "1B - Timed Precis Outline",
            "Progress Check for Learning",
            "95.00",
            "100.00",
            "1.00",
            "95.00",
            "100.00",
            "95.000%",
          ],
          [
            "09/29/2023",
            "09/21/2023",
            "6C - Character Defense Presentation",
            "Assessment of Learning",
            "90.00",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "09/27/2023",
            "09/26/2023",
            "1D- Vocab 21-22 Test",
            "Assessment of Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "AP English Language & Composition",
          weight: 6,
          multiplier: 1,
        },
      },
      {
        courseCode: "FLG12100",
        courseName: "French 2",
        studentGrade: 95,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/03/2023",
            "10/03/2023",
            "AL#6: PW (1C-Language Control)",
            "Assessment of Learning",
            "90.00",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "10/03/2023",
            "10/03/2023",
            "AL#5: PW (1B-Text Type)",
            "Assessment of Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
          [
            "09/27/2023",
            "09/27/2023",
            "PC#5: PW (1C-Language Control)",
            "Progress Check for Learning",
            "95.00",
            "100.00",
            "1.00",
            "95.00",
            "100.00",
            "95.000%",
          ],
          [
            "09/27/2023",
            "09/27/2023",
            "PC#4: PW (1B-Text Type)",
            "Progress Check for Learning",
            "85.00",
            "100.00",
            "1.00",
            "85.00",
            "100.00",
            "85.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "French 2",
          weight: 5,
          multiplier: 1,
        },
      },
      {
        courseCode: "MTH45305",
        courseName: "AP Calculus BC",
        studentGrade: 90,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/05/2023",
            " ",
            "Unit 3 AL",
            "Assessment of Learning",
            "80.00",
            "100.00",
            "1.00",
            "80.00",
            "100.00",
            "80.000%",
          ],
          [
            "09/28/2023",
            " ",
            "Unit 3 PC",
            "Progress Check for Learning",
            "85.00",
            "100.00",
            "1.00",
            "85.00",
            "100.00",
            "85.000%",
          ],
          [
            "09/22/2023",
            " ",
            "Formula Quiz AL",
            "Assessment of Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
          [
            "09/21/2023",
            " ",
            "Formula Quiz PC",
            "Progress Check for Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "AP Calculus BC",
          weight: 6,
          multiplier: 1,
        },
      },
      {
        courseCode: "SCI24300",
        courseName: "AP Chemistry",
        studentGrade: 95,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/02/2023",
            "10/02/2023",
            "Unit 2 Test: Advanced Covalent Bonding",
            "Assessment of Learning",
            "90.0",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "10/02/2023",
            "10/02/2023",
            "Unit 2 Test: Ionic/Covalent/Metallic Bonding",
            "Assessment of Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
          [
            "10/02/2023",
            "09/08/2023",
            "Unit 2 PWS",
            "Progress Check for Learning",
            "CNS",
            "100.00",
            "1.00",
            "0.00",
            "100.00",
            "0.00%",
          ],
          [
            "09/26/2023",
            "08/17/2023",
            "Overall Lab Grade",
            "Assessment of Learning",
            "95.00",
            "100.00",
            "1.00",
            "95.00",
            "100.00",
            "95.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "AP Chemistry",
          weight: 6,
          multiplier: 1,
        },
      },
      {
        courseCode: "SST23300",
        courseName: "AP US History",
        studentGrade: 91,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/03/2023",
            "10/03/2023",
            "Period 3 SAQ",
            "Assessment of Learning",
            "90.00",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "10/03/2023",
            "10/03/2023",
            "Period 3 Assessment",
            "Assessment of Learning",
            "90.00",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "09/29/2023",
            "09/29/2023",
            "Period 3 Progress Check",
            "Progress Check for Learning",
            "CNS",
            "100.00",
            "1.00",
            " ",
            "100.00",
            " ",
          ],
          [
            "09/29/2023",
            "09/29/2023",
            "Period 3 Vocab Check",
            "Progress Check for Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
          [
            "09/29/2023",
            "09/28/2023",
            "Period 3 Constitution Inquiry",
            "Assessment of Learning",
            "93.00",
            "100.00",
            "1.00",
            "93.00",
            "100.00",
            "93.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "AP US History",
          weight: 6,
          multiplier: 1,
        },
      },
    ],
  },
  2: {
    data: [
      {
        courseCode: "ELA13300",
        courseName: "AP English Language",
        studentGrade: 95,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/05/2023",
            "10/03/2023",
            "1B - Timed Precis",
            "Assessment of Learning",
            "95.00",
            "100.00",
            "1.00",
            "95.00",
            "100.00",
            "95.000%",
          ],
          [
            "10/05/2023",
            "10/03/2023",
            "1B - Timed Precis Outline",
            "Progress Check for Learning",
            "95.00",
            "100.00",
            "1.00",
            "95.00",
            "100.00",
            "95.000%",
          ],
          [
            "09/29/2023",
            "09/21/2023",
            "6C - Character Defense Presentation",
            "Assessment of Learning",
            "90.00",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "09/27/2023",
            "09/26/2023",
            "1D- Vocab 21-22 Test",
            "Assessment of Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "AP English Language & Composition",
          weight: 6,
          multiplier: 1,
        },
      },
      {
        courseCode: "FLG12100",
        courseName: "French 2",
        studentGrade: 95,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/03/2023",
            "10/03/2023",
            "AL#6: PW (1C-Language Control)",
            "Assessment of Learning",
            "90.00",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "10/03/2023",
            "10/03/2023",
            "AL#5: PW (1B-Text Type)",
            "Assessment of Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
          [
            "09/27/2023",
            "09/27/2023",
            "PC#5: PW (1C-Language Control)",
            "Progress Check for Learning",
            "95.00",
            "100.00",
            "1.00",
            "95.00",
            "100.00",
            "95.000%",
          ],
          [
            "09/27/2023",
            "09/27/2023",
            "PC#4: PW (1B-Text Type)",
            "Progress Check for Learning",
            "85.00",
            "100.00",
            "1.00",
            "85.00",
            "100.00",
            "85.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "French 2",
          weight: 5,
          multiplier: 1,
        },
      },
      {
        courseCode: "MTH45305",
        courseName: "AP Calculus BC",
        studentGrade: 90,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/05/2023",
            " ",
            "Unit 3 AL",
            "Assessment of Learning",
            "80.00",
            "100.00",
            "1.00",
            "80.00",
            "100.00",
            "80.000%",
          ],
          [
            "09/28/2023",
            " ",
            "Unit 3 PC",
            "Progress Check for Learning",
            "85.00",
            "100.00",
            "1.00",
            "85.00",
            "100.00",
            "85.000%",
          ],
          [
            "09/22/2023",
            " ",
            "Formula Quiz AL",
            "Assessment of Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
          [
            "09/21/2023",
            " ",
            "Formula Quiz PC",
            "Progress Check for Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "AP Calculus BC",
          weight: 6,
          multiplier: 1,
        },
      },
      {
        courseCode: "SCI24300",
        courseName: "AP Chemistry",
        studentGrade: 95,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/02/2023",
            "10/02/2023",
            "Unit 2 Test: Advanced Covalent Bonding",
            "Assessment of Learning",
            "90.0",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "10/02/2023",
            "10/02/2023",
            "Unit 2 Test: Ionic/Covalent/Metallic Bonding",
            "Assessment of Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
          [
            "10/02/2023",
            "09/08/2023",
            "Unit 2 PWS",
            "Progress Check for Learning",
            "CNS",
            "100.00",
            "1.00",
            "0.00",
            "100.00",
            "0.00%",
          ],
          [
            "09/26/2023",
            "08/17/2023",
            "Overall Lab Grade",
            "Assessment of Learning",
            "95.00",
            "100.00",
            "1.00",
            "95.00",
            "100.00",
            "95.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "AP Chemistry",
          weight: 6,
          multiplier: 1,
        },
      },
      {
        courseCode: "SST23300",
        courseName: "AP US History",
        studentGrade: 91,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/03/2023",
            "10/03/2023",
            "Period 3 SAQ",
            "Assessment of Learning",
            "90.00",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "10/03/2023",
            "10/03/2023",
            "Period 3 Assessment",
            "Assessment of Learning",
            "90.00",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "09/29/2023",
            "09/29/2023",
            "Period 3 Progress Check",
            "Progress Check for Learning",
            "CNS",
            "100.00",
            "1.00",
            " ",
            "100.00",
            " ",
          ],
          [
            "09/29/2023",
            "09/29/2023",
            "Period 3 Vocab Check",
            "Progress Check for Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
          [
            "09/29/2023",
            "09/28/2023",
            "Period 3 Constitution Inquiry",
            "Assessment of Learning",
            "93.00",
            "100.00",
            "1.00",
            "93.00",
            "100.00",
            "93.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "AP US History",
          weight: 6,
          multiplier: 1,
        },
      },
    ],
  },
  3: {
    data: [
      {
        courseCode: "ELA13300",
        courseName: "AP English Language",
        studentGrade: 95,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/05/2023",
            "10/03/2023",
            "1B - Timed Precis",
            "Assessment of Learning",
            "95.00",
            "100.00",
            "1.00",
            "95.00",
            "100.00",
            "95.000%",
          ],
          [
            "10/05/2023",
            "10/03/2023",
            "1B - Timed Precis Outline",
            "Progress Check for Learning",
            "95.00",
            "100.00",
            "1.00",
            "95.00",
            "100.00",
            "95.000%",
          ],
          [
            "09/29/2023",
            "09/21/2023",
            "6C - Character Defense Presentation",
            "Assessment of Learning",
            "90.00",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "09/27/2023",
            "09/26/2023",
            "1D- Vocab 21-22 Test",
            "Assessment of Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "AP English Language & Composition",
          weight: 6,
          multiplier: 1,
        },
      },
      {
        courseCode: "FLG12100",
        courseName: "French 2",
        studentGrade: 95,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/03/2023",
            "10/03/2023",
            "AL#6: PW (1C-Language Control)",
            "Assessment of Learning",
            "90.00",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "10/03/2023",
            "10/03/2023",
            "AL#5: PW (1B-Text Type)",
            "Assessment of Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
          [
            "09/27/2023",
            "09/27/2023",
            "PC#5: PW (1C-Language Control)",
            "Progress Check for Learning",
            "95.00",
            "100.00",
            "1.00",
            "95.00",
            "100.00",
            "95.000%",
          ],
          [
            "09/27/2023",
            "09/27/2023",
            "PC#4: PW (1B-Text Type)",
            "Progress Check for Learning",
            "85.00",
            "100.00",
            "1.00",
            "85.00",
            "100.00",
            "85.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "French 2",
          weight: 5,
          multiplier: 1,
        },
      },
      {
        courseCode: "MTH45305",
        courseName: "AP Calculus BC",
        studentGrade: 90,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/05/2023",
            " ",
            "Unit 3 AL",
            "Assessment of Learning",
            "80.00",
            "100.00",
            "1.00",
            "80.00",
            "100.00",
            "80.000%",
          ],
          [
            "09/28/2023",
            " ",
            "Unit 3 PC",
            "Progress Check for Learning",
            "85.00",
            "100.00",
            "1.00",
            "85.00",
            "100.00",
            "85.000%",
          ],
          [
            "09/22/2023",
            " ",
            "Formula Quiz AL",
            "Assessment of Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
          [
            "09/21/2023",
            " ",
            "Formula Quiz PC",
            "Progress Check for Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "AP Calculus BC",
          weight: 6,
          multiplier: 1,
        },
      },
      {
        courseCode: "SCI24300",
        courseName: "AP Chemistry",
        studentGrade: 95,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/02/2023",
            "10/02/2023",
            "Unit 2 Test: Advanced Covalent Bonding",
            "Assessment of Learning",
            "90.0",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "10/02/2023",
            "10/02/2023",
            "Unit 2 Test: Ionic/Covalent/Metallic Bonding",
            "Assessment of Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
          [
            "10/02/2023",
            "09/08/2023",
            "Unit 2 PWS",
            "Progress Check for Learning",
            "CNS",
            "100.00",
            "1.00",
            "0.00",
            "100.00",
            "0.00%",
          ],
          [
            "09/26/2023",
            "08/17/2023",
            "Overall Lab Grade",
            "Assessment of Learning",
            "95.00",
            "100.00",
            "1.00",
            "95.00",
            "100.00",
            "95.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "AP Chemistry",
          weight: 6,
          multiplier: 1,
        },
      },
      {
        courseCode: "SST23300",
        courseName: "AP US History",
        studentGrade: 91,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/03/2023",
            "10/03/2023",
            "Period 3 SAQ",
            "Assessment of Learning",
            "90.00",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "10/03/2023",
            "10/03/2023",
            "Period 3 Assessment",
            "Assessment of Learning",
            "90.00",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "09/29/2023",
            "09/29/2023",
            "Period 3 Progress Check",
            "Progress Check for Learning",
            "CNS",
            "100.00",
            "1.00",
            " ",
            "100.00",
            " ",
          ],
          [
            "09/29/2023",
            "09/29/2023",
            "Period 3 Vocab Check",
            "Progress Check for Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
          [
            "09/29/2023",
            "09/28/2023",
            "Period 3 Constitution Inquiry",
            "Assessment of Learning",
            "93.00",
            "100.00",
            "1.00",
            "93.00",
            "100.00",
            "93.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "AP US History",
          weight: 6,
          multiplier: 1,
        },
      },
    ],
  },
  4: {
    data: [
      {
        courseCode: "ELA13300",
        courseName: "AP English Language",
        studentGrade: 95,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/05/2023",
            "10/03/2023",
            "1B - Timed Precis",
            "Assessment of Learning",
            "95.00",
            "100.00",
            "1.00",
            "95.00",
            "100.00",
            "95.000%",
          ],
          [
            "10/05/2023",
            "10/03/2023",
            "1B - Timed Precis Outline",
            "Progress Check for Learning",
            "95.00",
            "100.00",
            "1.00",
            "95.00",
            "100.00",
            "95.000%",
          ],
          [
            "09/29/2023",
            "09/21/2023",
            "6C - Character Defense Presentation",
            "Assessment of Learning",
            "90.00",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "09/27/2023",
            "09/26/2023",
            "1D- Vocab 21-22 Test",
            "Assessment of Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "AP English Language & Composition",
          weight: 6,
          multiplier: 1,
        },
      },
      {
        courseCode: "FLG12100",
        courseName: "French 2",
        studentGrade: 95,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/03/2023",
            "10/03/2023",
            "AL#6: PW (1C-Language Control)",
            "Assessment of Learning",
            "90.00",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "10/03/2023",
            "10/03/2023",
            "AL#5: PW (1B-Text Type)",
            "Assessment of Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
          [
            "09/27/2023",
            "09/27/2023",
            "PC#5: PW (1C-Language Control)",
            "Progress Check for Learning",
            "95.00",
            "100.00",
            "1.00",
            "95.00",
            "100.00",
            "95.000%",
          ],
          [
            "09/27/2023",
            "09/27/2023",
            "PC#4: PW (1B-Text Type)",
            "Progress Check for Learning",
            "85.00",
            "100.00",
            "1.00",
            "85.00",
            "100.00",
            "85.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "French 2",
          weight: 5,
          multiplier: 1,
        },
      },
      {
        courseCode: "MTH45305",
        courseName: "AP Calculus BC",
        studentGrade: 90,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/05/2023",
            " ",
            "Unit 3 AL",
            "Assessment of Learning",
            "80.00",
            "100.00",
            "1.00",
            "80.00",
            "100.00",
            "80.000%",
          ],
          [
            "09/28/2023",
            " ",
            "Unit 3 PC",
            "Progress Check for Learning",
            "85.00",
            "100.00",
            "1.00",
            "85.00",
            "100.00",
            "85.000%",
          ],
          [
            "09/22/2023",
            " ",
            "Formula Quiz AL",
            "Assessment of Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
          [
            "09/21/2023",
            " ",
            "Formula Quiz PC",
            "Progress Check for Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "AP Calculus BC",
          weight: 6,
          multiplier: 1,
        },
      },
      {
        courseCode: "SCI24300",
        courseName: "AP Chemistry",
        studentGrade: 95,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/02/2023",
            "10/02/2023",
            "Unit 2 Test: Advanced Covalent Bonding",
            "Assessment of Learning",
            "90.0",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "10/02/2023",
            "10/02/2023",
            "Unit 2 Test: Ionic/Covalent/Metallic Bonding",
            "Assessment of Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
          [
            "10/02/2023",
            "09/08/2023",
            "Unit 2 PWS",
            "Progress Check for Learning",
            "CNS",
            "100.00",
            "1.00",
            "0.00",
            "100.00",
            "0.00%",
          ],
          [
            "09/26/2023",
            "08/17/2023",
            "Overall Lab Grade",
            "Assessment of Learning",
            "95.00",
            "100.00",
            "1.00",
            "95.00",
            "100.00",
            "95.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "AP Chemistry",
          weight: 6,
          multiplier: 1,
        },
      },
      {
        courseCode: "SST23300",
        courseName: "AP US History",
        studentGrade: 91,
        assignmentData: [
          [
            "Date Due",
            "Date Assigned",
            "Assignment",
            "Category",
            "Score",
            "Total Points",
            "Weight",
            "Weighted Score",
            "Weighted Total Points",
            "Percentage",
          ],
          [
            "10/03/2023",
            "10/03/2023",
            "Period 3 SAQ",
            "Assessment of Learning",
            "90.00",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "10/03/2023",
            "10/03/2023",
            "Period 3 Assessment",
            "Assessment of Learning",
            "90.00",
            "100.00",
            "1.00",
            "90.00",
            "100.00",
            "90.000%",
          ],
          [
            "09/29/2023",
            "09/29/2023",
            "Period 3 Progress Check",
            "Progress Check for Learning",
            "CNS",
            "100.00",
            "1.00",
            " ",
            "100.00",
            " ",
          ],
          [
            "09/29/2023",
            "09/29/2023",
            "Period 3 Vocab Check",
            "Progress Check for Learning",
            "100.0",
            "100.00",
            "1.00",
            "100.00",
            "100.00",
            "100.000%",
          ],
          [
            "09/29/2023",
            "09/28/2023",
            "Period 3 Constitution Inquiry",
            "Assessment of Learning",
            "93.00",
            "100.00",
            "1.00",
            "93.00",
            "100.00",
            "93.000%",
          ],
        ],
        noWeight: false,
        weightDetails: {
          name: "AP US History",
          weight: 6,
          multiplier: 1,
        },
      },
    ],
  },
};

export const demoTransData = {
  1: {
    transPerGradeData: [
      ["Year:", "2023-2024", "", "", "Grade:", "11"],
      ["Building:", "Lebanon Trail High School"],
    ],
    transPerGradeData2: [
      ["Course", "Description", "SEM1", "SEM2", "FIN", "Credit"],
      ["T03500100 - 246", "Art I", "P", "P", "", "1.0000"],
    ],
  },
  2: {
    transPerGradeData: [
      ["Year:", "2023-2024", "", "", "Grade:", "11"],
      ["Building:", "Lebanon Trail High School"],
    ],
    transPerGradeData2: [
      ["Course", "Description", "SEM1", "SEM2", "FIN", "Credit"],
      ["T03500100 - 246", "Art I", "100", "100", "", "1.0000"],
    ],
  },
  3: {
    transPerGradeData: [
      ["Year:", "2023-2024", "", "", "Grade:", "11"],
      ["Building:", "Lebanon Trail High School"],
    ],
    transPerGradeData2: [
      ["Course", "Description", "SEM1", "SEM2", "FIN", "Credit"],
      ["T03500100 - 246", "Art I", "100", "100", "", "1.0000"],
    ],
  },
  transPerRankData: [
    ["GPA Type", "GPA", "Rank"],
    ["Weighted GPA", "4.800", ""],
    ["4.0 College GPA", "3.9000", ""],
  ],
};
